import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { render, validate, type Diagnostic, type RenderResult } from '@sculpt/core';
import { routeMidpoint, type PositionedNode } from '@sculpt/layout';
import { WorkspaceHistory, addEdgeWaypoint, alignNodes, applyNodeResize, deleteEdgeWaypoint, distributeNodes, insertEdgeWaypoint, matchNodeSize, moveEdgeWaypoint, moveNode, resizeNode, translateNodes, updateEdgeGeometry, type Alignment, type Distribution, type EditorSelection, type MatchDimension, type NodeFrame, type ViewType, type Workspace } from '@sculpt/workspace';
import { DiagramCanvas } from './components/DiagramCanvas';
import { Inspector } from './components/Inspector';
import { PrecisionToolbar } from './components/PrecisionToolbar';
import { useWorkspace } from './workspace/useWorkspace';
import './styles.css';
const frame = (node: PositionedNode, workspace: Workspace): NodeFrame => ({ ...node, locked: workspace.layout.nodes[node.id]?.positionLocked ?? false });
function App() {
  const { workspace, controller, viewType, changeOrigin } = useWorkspace(); const history = useMemo(() => new WorkspaceHistory(), [controller]); const [historyVersion, setHistoryVersion] = useState(0); const [result, setResult] = useState<RenderResult>(); const [diagnostic, setDiagnostic] = useState<Diagnostic>(); const [selection, setSelection] = useState<EditorSelection>();
  useEffect(() => { if (!workspace) return; const timer = setTimeout(() => { const validation = validate(workspace.source); if (!validation.valid) { setDiagnostic(validation.diagnostics[0]); return; } try { setResult(render('preview', workspace.source, { theme: workspace.theme, metadata: workspace.layout })); setDiagnostic(undefined); } catch (error) { setDiagnostic({ code: 'RENDER', message: error instanceof Error ? error.message : 'Unable to render this diagram.', stage: 'render', severity: 'error' }); } }, 80); return () => clearTimeout(timer); }, [workspace]);
  useEffect(() => { if (changeOrigin === 'remote') { history.clear(); setHistoryVersion((value) => value + 1); } }, [changeOrigin, history, workspace?.revision]);
  const apply = (recipe: (current: Workspace) => Workspace, record = true) => { const previous = controller.current; if (!previous) return; const next = recipe(previous); if (next === previous) return; const committed = controller.update(() => next); if (record) history.push(previous, committed); setHistoryVersion((value) => value + 1); };
  const undo = () => { const current = controller.current; const snapshot = current ? history.undo(current) : undefined; if (snapshot) controller.update(() => snapshot); setHistoryVersion((value) => value + 1); }; const redo = () => { const current = controller.current; const snapshot = current ? history.redo(current) : undefined; if (snapshot) controller.update(() => snapshot); setHistoryVersion((value) => value + 1); };
  useEffect(() => { const handler = (event: globalThis.KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target?.matches('textarea,input,select,[contenteditable="true"]')) return; const modifier = event.ctrlKey || event.metaKey; if (!modifier || event.key.toLowerCase() !== 'z' && event.key.toLowerCase() !== 'y') return; event.preventDefault(); if (event.key.toLowerCase() === 'y' || event.shiftKey) redo(); else undo(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); });
  if (!workspace || !result) return <main className="loading">Loading SCULPT workspace…</main>;
  const selectedFrames = selection?.type === 'nodes' ? result.layout.nodes.filter((node) => selection.nodeIds.includes(node.id)).map((node) => frame(node, workspace)) : [];
  const alignment = (value: Alignment) => apply((current) => alignNodes(current, selectedFrames, value)); const distribution = (value: Distribution) => apply((current) => distributeNodes(current, selectedFrames, value)); const match = (value: MatchDimension) => { if (selection?.type === 'nodes') apply((current) => matchNodeSize(current, selectedFrames, selection.primaryNodeId, value)); };
  const openView = (type: ViewType) => window.open(`/workspace/${encodeURIComponent(workspace.id)}?view=${type}`, '_blank', 'noopener'); const hasEditor = viewType === 'editor' || viewType === 'split'; const hasCanvas = viewType !== 'editor'; const hasInspector = viewType === 'inspector' || viewType === 'split'; const editable = viewType === 'split' || viewType === 'inspector'; const chrome = viewType !== 'presentation';
  const edgePatch = (edgeId: string, patch: Partial<Workspace['layout']['edges'][string]>) => apply((current) => { if (patch.routingLocked !== undefined) { const currentEdge = current.layout.edges[edgeId] ?? { routing: 'auto' as const }; return { ...current, layout: { ...current.layout, edges: { ...current.layout.edges, [edgeId]: { ...currentEdge, ...patch } } } }; } return updateEdgeGeometry(current, edgeId, patch.routing === 'orthogonal' ? { ...patch, waypoints: [] } : patch); });
  const addWaypoint = (edgeId: string) => { const route = result.layout.edges.find((edge) => edge.id === edgeId)?.points; const point = route ? routeMidpoint(route) : undefined; if (point) apply((current) => addEdgeWaypoint(current, edgeId, point)); };
  return <main className={`app ${workspace.theme === 'dark' ? 'dark' : ''} view-${viewType}`}>{chrome && <header><div className="brand"><span className="mark">S</span><div><strong>SCULPT</strong><small>Write the structure. Sculpt the diagram.</small></div></div><nav><select aria-label="Open view" defaultValue="" onChange={(event) => { openView(event.target.value as ViewType); event.target.value = ''; }}><option value="" disabled>Open View…</option>{(['editor','preview','split','inspector','presentation'] as const).map((type) => <option key={type} value={type}>{type[0]?.toUpperCase()}{type.slice(1)}</option>)}</select><button onClick={() => controller.update((current) => ({ ...current, theme: current.theme === 'dark' ? 'light' : 'dark' }))}>{workspace.theme === 'dark' ? 'Light' : 'Dark'} mode</button></nav></header>}
    <section className={`workspace-shell ${!hasEditor ? 'no-editor' : ''} ${!hasInspector ? 'no-inspector' : ''}`}>{hasEditor && <article className="panel editor"><div className="panel-title"><span>Source</span><button onClick={() => void navigator.clipboard.writeText(workspace.source)}>Copy</button></div><textarea aria-label="Diagram source" spellCheck={false} value={workspace.source} onChange={(event) => controller.update((current) => ({ ...current, source: event.target.value }))}/>{diagnostic && <div className="error"><strong>{diagnostic.code}</strong> {diagnostic.message}{diagnostic.range && <span>Line {diagnostic.range.start.line}, column {diagnostic.range.start.column}</span>}</div>}</article>}
      {hasCanvas && <article className="panel preview"><div className="panel-title"><span>{viewType === 'presentation' ? workspace.name : 'Canvas'}</span><span className="mode">{workspace.layout.mode}</span></div>{editable && <PrecisionToolbar key={historyVersion} selection={selection} canUndo={history.canUndo} canRedo={history.canRedo} onUndo={undo} onRedo={redo} onAlign={alignment} onDistribute={distribution} onMatch={match}/>}<DiagramCanvas svg={result.svg} layout={result.layout} workspace={workspace} editable={editable} selection={selection} onSelection={setSelection} onTranslate={(nodes, dx, dy, primary, transient, snapResolved) => apply((current) => translateNodes(current, nodes.map((node) => frame(node, workspace)), dx, dy, primary, !snapResolved), !transient)} onResize={(node, geometry, transient) => apply((current) => applyNodeResize(current, node.id, geometry, node), !transient)} onWaypointMove={(edgeId, index, point) => apply((current) => moveEdgeWaypoint(current, edgeId, index, point), false)} onWaypointDelete={(edgeId, index) => apply((current) => deleteEdgeWaypoint(current, edgeId, index))} onWaypointInsert={(edgeId, point, segmentIndex) => apply((current) => insertEdgeWaypoint(current, edgeId, point, segmentIndex))} onGestureStart={() => history.begin(controller.current ?? workspace)} onGestureEnd={() => { if (controller.current) history.commit(controller.current); setHistoryVersion((value) => value + 1); }}/></article>}
      {hasInspector && <Inspector workspace={workspace} ast={result.ast} layout={result.layout} selection={selection} onPosition={(id, x, y) => apply((current) => moveNode(current, id, x, y))} onSize={(id, width, height) => { const node = result.layout.nodes.find((value) => value.id === id); if (node) apply((current) => resizeNode(current, frame(node, current), width, height)); }} onLock={(id, locked) => apply((current) => ({ ...current, layout: { ...current.layout, nodes: { ...current.layout.nodes, [id]: { ...current.layout.nodes[id], positionLocked: locked } } } }))} onGrid={(grid) => controller.update((current) => ({ ...current, layout: { ...current.layout, grid: { ...current.layout.grid, ...grid } } }))} onAlign={alignment} onDistribute={distribution} onMatch={match} onEdge={edgePatch} onAddWaypoint={addWaypoint}/>}</section>
    {chrome && <footer><span className={diagnostic ? 'bad' : 'good'}>{diagnostic ? 'Geometry error' : `Workspace r${workspace.revision}`}</span><span>Ctrl/Cmd-click multi-select · drag empty canvas to marquee · Alt-drag to pan</span></footer>}</main>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
