import { useRef, useState, type KeyboardEvent, type PointerEvent } from 'react';
import type { Selection, Workspace } from '@sculpt/workspace';
interface Props { svg: string; workspace: Workspace; editable: boolean; selection: Selection; onSelection(selection: Selection): void; onMove(id: string, x: number, y: number): void }
interface Drag { id?: string; pointerX: number; pointerY: number; diagramX?: number; diagramY?: number; nodeX?: number; nodeY?: number; panX: number; panY: number }
export function DiagramCanvas({ svg, workspace, editable, selection, onSelection, onMove }: Props) {
  const [scale, setScale] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const drag = useRef<Drag | undefined>(undefined);
  const point = (event: PointerEvent<HTMLDivElement>) => { const svgElement = event.currentTarget.querySelector('svg'); if (!svgElement) return; const value = svgElement.createSVGPoint(); value.x = event.clientX; value.y = event.clientY; const matrix = svgElement.getScreenCTM()?.inverse(); return matrix ? value.matrixTransform(matrix) : undefined; };
  const down = (event: PointerEvent<HTMLDivElement>) => { const element = (event.target as Element).closest<SVGGElement>('[data-node-id]'); const id = element?.dataset.nodeId; if (id) onSelection({ type: 'node', id }); else onSelection(undefined); const current = id ? workspace.layout.nodes[id] : undefined; const diagram = point(event); const text = element?.querySelector('text'); const nodeX = current?.x ?? Number(text?.getAttribute('x')); const nodeY = current?.y ?? Number(text?.getAttribute('y')); if (id && editable && current?.x === undefined && Number.isFinite(nodeX) && Number.isFinite(nodeY)) onMove(id, nodeX, nodeY); drag.current = { ...(id && editable && !current?.positionLocked && diagram && Number.isFinite(nodeX) && Number.isFinite(nodeY) ? { id, diagramX: diagram.x, diagramY: diagram.y, nodeX, nodeY } : {}), pointerX: event.clientX, pointerY: event.clientY, panX: pan.x, panY: pan.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: PointerEvent<HTMLDivElement>) => { const value = drag.current; if (!value) return; if (value.id && value.diagramX !== undefined && value.diagramY !== undefined && value.nodeX !== undefined && value.nodeY !== undefined) { const next = point(event); if (next) onMove(value.id, value.nodeX + next.x - value.diagramX, value.nodeY + next.y - value.diagramY); } else setPan({ x: value.panX + event.clientX - value.pointerX, y: value.panY + event.clientY - value.pointerY }); };
  const key = (event: KeyboardEvent<HTMLDivElement>) => { if (!editable || selection?.type !== 'node' || workspace.layout.nodes[selection.id]?.positionLocked) return; const deltas: Record<string, [number, number]> = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }; const delta = deltas[event.key]; if (!delta) return; event.preventDefault(); const selected = event.currentTarget.querySelector(`[data-node-id="${CSS.escape(selection.id)}"] text`); const geometry = workspace.layout.nodes[selection.id]; const x = geometry?.x ?? Number(selected?.getAttribute('x')); const y = geometry?.y ?? Number(selected?.getAttribute('y')); if (Number.isFinite(x) && Number.isFinite(y)) onMove(selection.id, x + delta[0] * (event.shiftKey ? 10 : 1), y + delta[1] * (event.shiftKey ? 10 : 1)); };
  return <div className={`canvas ${workspace.layout.grid.visible ? 'grid' : ''}`} style={{ '--grid': `${workspace.layout.grid.spacing * scale}px` } as React.CSSProperties} tabIndex={0} onKeyDown={key} onWheel={(event) => { event.preventDefault(); setScale((value) => Math.min(3, Math.max(.3, value - event.deltaY * .001))); }} onPointerDown={down} onPointerMove={move} onPointerUp={() => { drag.current = undefined; }}><div className="diagram" style={{ transform: `translate(${pan.x}px,${pan.y}px) scale(${scale})` }} dangerouslySetInnerHTML={{ __html: svg }}/><div className="zoom-tools"><button onClick={() => setScale(Math.max(.3, scale - .15))}>−</button><output>{Math.round(scale * 100)}%</output><button onClick={() => setScale(Math.min(3, scale + .15))}>+</button><button onClick={() => { setScale(1); setPan({ x: 0, y: 0 }); }}>Fit</button></div></div>;
}
