import { useRef, useState, type CSSProperties, type KeyboardEvent, type PointerEvent } from 'react';
import type { LayoutResult, Point, PositionedNode } from '@sculpt/layout';
import type { EditorSelection, Workspace } from '@sculpt/workspace';
interface Props { svg: string; layout: LayoutResult; workspace: Workspace; editable: boolean; selection: EditorSelection; onSelection(selection: EditorSelection): void; onTranslate(frames: PositionedNode[], dx: number, dy: number, primaryId: string, transient: boolean): void; onWaypointMove(edgeId: string, index: number, point: Point): void; onWaypointDelete(edgeId: string, index: number): void; onGestureStart(): void; onGestureEnd(): void }
type Gesture = { type: 'nodes'; start: Point; frames: PositionedNode[]; primaryId: string; moved: boolean } | { type: 'waypoint'; edgeId: string; index: number; routing: string } | { type: 'marquee'; start: Point; additive: boolean; original: string[] } | { type: 'pan'; x: number; y: number; panX: number; panY: number };
interface Marquee { start: Point; end: Point }
const svgPoints = (points: Point[]) => points.map((point) => `${point.x},${point.y}`).join(' ');
const intersects = (node: PositionedNode, box: Marquee) => { const left = Math.min(box.start.x, box.end.x); const right = Math.max(box.start.x, box.end.x); const top = Math.min(box.start.y, box.end.y); const bottom = Math.max(box.start.y, box.end.y); return node.x + node.width / 2 >= left && node.x - node.width / 2 <= right && node.y + node.height / 2 >= top && node.y - node.height / 2 <= bottom; };
export function DiagramCanvas({ svg, layout, workspace, editable, selection, onSelection, onTranslate, onWaypointMove, onWaypointDelete, onGestureStart, onGestureEnd }: Props) {
  const [scale, setScale] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [marquee, setMarquee] = useState<Marquee>(); const gesture = useRef<Gesture | undefined>(undefined);
  const diagramPoint = (event: PointerEvent<HTMLDivElement>): Point | undefined => { const svgElement = event.currentTarget.querySelector<SVGSVGElement>('.diagram-output svg'); if (!svgElement) return; const value = svgElement.createSVGPoint(); value.x = event.clientX; value.y = event.clientY; const matrix = svgElement.getScreenCTM()?.inverse(); return matrix ? value.matrixTransform(matrix) : undefined; };
  const selectedIds = selection?.type === 'nodes' ? selection.nodeIds : [];
  const pointerDown = (event: PointerEvent<HTMLDivElement>) => {
    const target = event.target as Element; const nodeId = target.closest<SVGElement>('[data-overlay-node]')?.dataset.overlayNode; const edgeId = target.closest<SVGElement>('[data-overlay-edge]')?.dataset.overlayEdge; const waypointValue = target.closest<SVGElement>('[data-waypoint]')?.getAttribute('data-waypoint'); const point = diagramPoint(event); const additive = event.ctrlKey || event.metaKey;
    if (waypointValue && point) { const [selectedEdge, rawIndex] = waypointValue.split(':'); const index = Number(rawIndex); if (selectedEdge && Number.isInteger(index)) { onSelection({ type: 'edge', edgeId: selectedEdge, waypointIndex: index }); if (!workspace.layout.edges[selectedEdge]?.routingLocked) { gesture.current = { type: 'waypoint', edgeId: selectedEdge, index, routing: workspace.layout.edges[selectedEdge]?.routing ?? 'manual' }; onGestureStart(); } } }
    else if (nodeId && point) { let ids: string[]; let primary = nodeId; if (additive) { ids = selectedIds.includes(nodeId) ? selectedIds.filter((id) => id !== nodeId) : [...selectedIds, nodeId]; primary = selection?.type === 'nodes' && ids.includes(selection.primaryNodeId) ? selection.primaryNodeId : nodeId; } else ids = selectedIds.includes(nodeId) ? selectedIds : [nodeId]; if (ids.length) onSelection({ type: 'nodes', nodeIds: [...new Set(ids)], primaryNodeId: primary }); else onSelection(undefined); if (editable && !additive && ids.includes(nodeId)) { const frames = layout.nodes.filter((node) => ids.includes(node.id)); gesture.current = { type: 'nodes', start: point, frames, primaryId: nodeId, moved: false }; onGestureStart(); } }
    else if (edgeId) onSelection({ type: 'edge', edgeId });
    else if ((event.button === 1 || event.altKey)) gesture.current = { type: 'pan', x: event.clientX, y: event.clientY, panX: pan.x, panY: pan.y };
    else if (editable && point) { const original = additive && selection?.type === 'nodes' ? selection.nodeIds : []; gesture.current = { type: 'marquee', start: point, additive, original }; setMarquee({ start: point, end: point }); if (!additive) onSelection(undefined); }
    else onSelection(undefined);
    event.currentTarget.setPointerCapture(event.pointerId);
  };
  const pointerMove = (event: PointerEvent<HTMLDivElement>) => { const current = gesture.current; if (!current) return; if (current.type === 'pan') { setPan({ x: current.panX + event.clientX - current.x, y: current.panY + event.clientY - current.y }); return; } const point = diagramPoint(event); if (!point) return; if (current.type === 'nodes') { const dx = point.x - current.start.x; const dy = point.y - current.start.y; if (Math.hypot(dx, dy) > 1) current.moved = true; if (current.moved) onTranslate(current.frames, dx, dy, current.primaryId, true); } if (current.type === 'marquee') { const box = { start: current.start, end: point }; setMarquee(box); const inside = layout.nodes.filter((node) => intersects(node, box)).map((node) => node.id); const ids = [...new Set([...current.original, ...inside])]; onSelection(ids.length ? { type: 'nodes', nodeIds: ids, primaryNodeId: ids.at(-1)! } : undefined); } if (current.type === 'waypoint') { let next = point; if (current.routing === 'orthogonal') { const route = layout.edges.find((edge) => edge.id === current.edgeId)?.points; const previous = route?.[current.index]; const following = route?.[current.index + 2]; if (previous && following) { const candidates = [{ x: previous.x, y: following.y }, { x: following.x, y: previous.y }]; next = candidates.sort((a, b) => Math.hypot(a.x - point.x, a.y - point.y) - Math.hypot(b.x - point.x, b.y - point.y))[0] ?? point; } } onWaypointMove(current.edgeId, current.index, next); } };
  const pointerUp = () => { const current = gesture.current; if (current?.type === 'nodes') { if (!current.moved) onSelection({ type: 'nodes', nodeIds: [current.primaryId], primaryNodeId: current.primaryId }); onGestureEnd(); } else if (current?.type === 'waypoint') onGestureEnd(); gesture.current = undefined; setMarquee(undefined); };
  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!editable) return; if (event.key === 'Escape') { onSelection(undefined); return; } if ((event.key === 'Delete' || event.key === 'Backspace') && selection?.type === 'edge' && selection.waypointIndex !== undefined) { event.preventDefault(); onWaypointDelete(selection.edgeId, selection.waypointIndex); onSelection({ type: 'edge', edgeId: selection.edgeId }); return; } if (selection?.type !== 'nodes') return; const deltas: Record<string, [number, number]> = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }; const delta = deltas[event.key]; if (!delta) return; event.preventDefault(); const amount = event.shiftKey ? 10 : 1; onTranslate(layout.nodes.filter((node) => selection.nodeIds.includes(node.id)), delta[0] * amount, delta[1] * amount, selection.primaryNodeId, false); };
  const selectedEdge = selection?.type === 'edge' ? selection.edgeId : undefined; const selectedWaypoints = selectedEdge ? workspace.layout.edges[selectedEdge]?.waypoints ?? [] : [];
  return <div className={`canvas ${workspace.layout.grid.visible ? 'grid' : ''}`} style={{ '--grid': `${workspace.layout.grid.spacing * scale}px` } as CSSProperties} tabIndex={0} onKeyDown={keyDown} onWheel={(event) => { event.preventDefault(); setScale((value) => Math.min(3, Math.max(.3, value - event.deltaY * .001))); }} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp}>
    <div className="diagram" style={{ transform: `translate(${pan.x}px,${pan.y}px) scale(${scale})` }}><div className="diagram-output" dangerouslySetInnerHTML={{ __html: svg }}/>{editable && <svg className="interaction-overlay" viewBox={`${layout.x} ${layout.y} ${layout.width} ${layout.height}`} aria-label="Diagram interaction layer">
      {layout.edges.map((edge) => <g key={edge.id}><polyline data-overlay-edge={edge.id} className="edge-hit" points={svgPoints(edge.points)}/>{selectedEdge === edge.id && <polyline className="edge-selected" points={svgPoints(edge.points)}/>}</g>)}
      {layout.nodes.map((node) => <rect key={node.id} data-overlay-node={node.id} className={`node-hit ${selectedIds.includes(node.id) ? 'selected' : ''} ${workspace.layout.nodes[node.id]?.positionLocked ? 'locked' : ''}`} x={node.x - node.width / 2} y={node.y - node.height / 2} width={node.width} height={node.height} rx="5"/>)}
      {selectedEdge && selectedWaypoints.map((point, index) => <circle key={`${selectedEdge}-${index}`} data-waypoint={`${selectedEdge}:${index}`} className={`waypoint ${selection?.type === 'edge' && selection.waypointIndex === index ? 'selected' : ''}`} cx={point.x} cy={point.y} r={6 / scale}/>)}
      {marquee && <rect className="marquee" x={Math.min(marquee.start.x, marquee.end.x)} y={Math.min(marquee.start.y, marquee.end.y)} width={Math.abs(marquee.end.x - marquee.start.x)} height={Math.abs(marquee.end.y - marquee.start.y)}/>} </svg>}</div>
    <div className="zoom-tools"><button aria-label="Zoom out" onClick={() => setScale(Math.max(.3, scale - .15))}>−</button><output>{Math.round(scale * 100)}%</output><button aria-label="Zoom in" onClick={() => setScale(Math.min(3, scale + .15))}>+</button><button onClick={() => { setScale(1); setPan({ x: 0, y: 0 }); }}>Fit</button></div></div>;
}
