import { useCallback, useEffect, useRef, useState, type CSSProperties, type KeyboardEvent, type MouseEvent, type PointerEvent } from 'react';
import type { LayoutResult, Point, PositionedNode } from '@sculpt/layout';
import { MAX_ZOOM, MIN_ZOOM, ZOOM_STEP, applyResizeSnap, boundsFromPoints, calculateFitScale, calculateViewportTransform, centerLockedResize, clampZoom, createNodeSelection, nearestRouteSegment, nodeBounds, resizeFromHandle, selectionBounds, snapBounds, snapResize, toggleNodeSelection, type AlignmentGuide, type Bounds, type EditorSelection, type ResizeHandle, type ResizeResult, type Workspace } from '@sculpt/workspace';
import { EditorOverlay } from './EditorOverlay';
interface Props { svg: string; layout: LayoutResult; workspace: Workspace; editable: boolean; selection: EditorSelection; onSelection(selection: EditorSelection): void; onTranslate(frames: PositionedNode[], dx: number, dy: number, primaryId: string, transient: boolean, snapResolved?: boolean): void; onResize(node: PositionedNode, result: ResizeResult, transient: boolean): void; onWaypointMove(edgeId: string, index: number, point: Point): void; onWaypointDelete(edgeId: string, index: number): void; onWaypointInsert(edgeId: string, point: Point, segmentIndex: number): void; onGestureStart(): void; onGestureEnd(): void }
interface GestureCoordinateFrame { screenToDiagram: DOMMatrix }
type Gesture =
  | { type: 'nodes'; frame: GestureCoordinateFrame; start: Point; frames: PositionedNode[]; primaryId: string; moved: boolean; bounds: Bounds; targets: Array<{ id: string; bounds: Bounds }> }
  | { type: 'resize'; frame: GestureCoordinateFrame; start: Point; node: PositionedNode; handle: ResizeHandle; moved: boolean; targets: Array<{ id: string; bounds: Bounds }> }
  | { type: 'waypoint'; frame: GestureCoordinateFrame; edgeId: string; index: number; routing: string; moved: boolean }
  | { type: 'marquee'; frame: GestureCoordinateFrame; start: Point; additive: boolean; original: string[] }
  | { type: 'pan'; x: number; y: number; panX: number; panY: number };
interface Marquee { start: Point; end: Point }
const intersects = (node: PositionedNode, box: Marquee) => node.x + node.width / 2 >= Math.min(box.start.x, box.end.x) && node.x - node.width / 2 <= Math.max(box.start.x, box.end.x) && node.y + node.height / 2 >= Math.min(box.start.y, box.end.y) && node.y - node.height / 2 <= Math.max(box.start.y, box.end.y);
const layoutBounds = (layout: LayoutResult): Bounds => ({ left: layout.x, right: layout.x + layout.width, top: layout.y, bottom: layout.y + layout.height, x: layout.x + layout.width / 2, y: layout.y + layout.height / 2, width: layout.width, height: layout.height });
export function DiagramCanvas({ svg, layout, workspace, editable, selection, onSelection, onTranslate, onResize, onWaypointMove, onWaypointDelete, onWaypointInsert, onGestureStart, onGestureEnd }: Props) {
  const canvasRef = useRef<HTMLDivElement | null>(null); const [scale, setScale] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [viewportMode, setViewportMode] = useState<'fit' | 'manual'>('fit'); const viewportModeRef = useRef<'fit' | 'manual'>('fit'); const [objectSnap, setObjectSnap] = useState(true); const [guides, setGuides] = useState<AlignmentGuide[]>([]); const [marquee, setMarquee] = useState<Marquee>(); const gesture = useRef<Gesture | undefined>(undefined);
  const setMode = (mode: 'fit' | 'manual') => { viewportModeRef.current = mode; setViewportMode(mode); };
  const fit = useCallback(() => { const canvas = canvasRef.current; if (!canvas) return; setScale(calculateFitScale({ width: canvas.clientWidth, height: canvas.clientHeight }, layout)); setPan({ x: 0, y: 0 }); }, [layout]);
  useEffect(() => { if (viewportMode !== 'fit') return; fit(); const canvas = canvasRef.current; if (!canvas) return; const observer = new ResizeObserver(() => { if (viewportModeRef.current === 'fit') fit(); }); observer.observe(canvas); return () => observer.disconnect(); }, [fit, viewportMode]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || !editable) return; const preventSelection = (event: Event) => event.preventDefault(); canvas.addEventListener('selectstart', preventSelection); return () => canvas.removeEventListener('selectstart', preventSelection); }, [editable]);
  const captureFrame = (element: HTMLDivElement): GestureCoordinateFrame | undefined => { const matrix = element.querySelector<SVGSVGElement>('.diagram-output svg')?.getScreenCTM()?.inverse(); return matrix ? { screenToDiagram: matrix } : undefined; };
  const diagramPoint = (clientX: number, clientY: number, frame: GestureCoordinateFrame): Point => { const point = new DOMPoint(clientX, clientY).matrixTransform(frame.screenToDiagram); return { x: point.x, y: point.y }; };
  const selectedIds = selection?.type === 'nodes' ? selection.nodeIds : [];
  const clearNativeSelection = () => window.getSelection()?.removeAllRanges();
  const snapTargets = (excluded: string[]) => layout.nodes.filter((node) => !excluded.includes(node.id)).flatMap((node) => { const bounds = nodeBounds(node); return bounds ? [{ id: node.id, bounds }] : []; });
  const pointerDown = (event: PointerEvent<HTMLDivElement>) => {
    const target = event.target as Element; if (target.closest('button, input, select, textarea')) return; if (editable) { event.preventDefault(); clearNativeSelection(); } const resizeHandle = target.closest<SVGElement>('[data-resize-handle]')?.dataset.resizeHandle as ResizeHandle | undefined; const nodeId = target.closest<SVGElement>('[data-overlay-node]')?.dataset.overlayNode; const waypointValue = target.closest<SVGElement>('[data-waypoint]')?.getAttribute('data-waypoint'); const edgeId = target.closest<SVGElement>('[data-overlay-edge]')?.dataset.overlayEdge; const frame = captureFrame(event.currentTarget); const point = frame ? diagramPoint(event.clientX, event.clientY, frame) : undefined; const additive = event.ctrlKey || event.metaKey;
    if (resizeHandle && point && frame && selection?.type === 'nodes' && selection.nodeIds.length === 1) { const node = layout.nodes.find((value) => value.id === selection.primaryNodeId); if (node) { setMode('manual'); gesture.current = { type: 'resize', frame, start: point, node, handle: resizeHandle, moved: false, targets: snapTargets([node.id]) }; onGestureStart(); } }
    else if (waypointValue && point && frame) { const [selectedEdge, rawIndex] = waypointValue.split(':'); const index = Number(rawIndex); if (selectedEdge && Number.isInteger(index)) { onSelection({ type: 'edge', edgeId: selectedEdge, waypointIndex: index }); if (!workspace.layout.edges[selectedEdge]?.routingLocked) { setMode('manual'); gesture.current = { type: 'waypoint', frame, edgeId: selectedEdge, index, routing: workspace.layout.edges[selectedEdge]?.routing ?? 'manual', moved: false }; onGestureStart(); } } }
    else if (nodeId && point && frame) { const next = additive ? toggleNodeSelection(selection, nodeId) : createNodeSelection(selectedIds.includes(nodeId) ? selectedIds : [nodeId], nodeId); onSelection(next); const ids = next?.type === 'nodes' ? next.nodeIds : []; if (editable && !additive && ids.includes(nodeId)) { const selectedFrames = layout.nodes.filter((node) => ids.includes(node.id)); const frames = selectedFrames.filter((node) => !workspace.layout.nodes[node.id]?.positionLocked); const bounds = selectionBounds(frames.map((node) => ({ ...node, locked: false }))); if (bounds && frames.length) { setMode('manual'); gesture.current = { type: 'nodes', frame, start: point, frames, primaryId: nodeId, moved: false, bounds, targets: snapTargets(frames.map((node) => node.id)) }; onGestureStart(); } } }
    else if (edgeId) onSelection({ type: 'edge', edgeId });
    else if (event.button === 1 || event.altKey) { setMode('manual'); gesture.current = { type: 'pan', x: event.clientX, y: event.clientY, panX: pan.x, panY: pan.y }; }
    else if (editable && point && frame) { setMode('manual'); const original = additive && selection?.type === 'nodes' ? selection.nodeIds : []; gesture.current = { type: 'marquee', frame, start: point, additive, original }; setMarquee({ start: point, end: point }); if (!additive) onSelection(undefined); }
    else onSelection(undefined); if (gesture.current) event.currentTarget.setPointerCapture(event.pointerId);
  };
  const pointerMove = (event: PointerEvent<HTMLDivElement>) => { const current = gesture.current; if (!current) return; if (current.type === 'pan') { setPan({ x: current.panX + event.clientX - current.x, y: current.panY + event.clientY - current.y }); return; } const point = diagramPoint(event.clientX, event.clientY, current.frame);
    if (current.type === 'nodes') { let dx = point.x - current.start.x; let dy = point.y - current.start.y; if (!current.moved && Math.hypot(dx, dy) <= 1) { setGuides([]); return; } current.moved = true; const intended = { ...current.bounds, left: current.bounds.left + dx, right: current.bounds.right + dx, top: current.bounds.top + dy, bottom: current.bounds.bottom + dy, x: current.bounds.x + dx, y: current.bounds.y + dy }; const snapped = snapBounds(intended, objectSnap ? current.targets : [], scale, 6, { enabled: workspace.layout.grid.snap, spacing: workspace.layout.grid.spacing }); dx += snapped.dx; dy += snapped.dy; setGuides(snapped.guides); onTranslate(current.frames, dx, dy, current.primaryId, true, true); }
    if (current.type === 'resize') { const rawDx = point.x - current.start.x; const rawDy = point.y - current.start.y; if (!current.moved && Math.hypot(rawDx, rawDy) <= 1) { setGuides([]); return; } current.moved = true; const locked = workspace.layout.nodes[current.node.id]?.positionLocked ?? false; const rawIntended = resizeFromHandle(current.node, current.handle, rawDx, rawDy); const intended = rawIntended && locked ? centerLockedResize(current.node, rawIntended) : rawIntended; const original = nodeBounds(current.node); const bounds = intended ? nodeBounds(intended) : undefined; if (intended && original && bounds) { const snapped = snapResize(original, bounds, current.handle, objectSnap ? current.targets : [], scale, 6, { enabled: workspace.layout.grid.snap, spacing: workspace.layout.grid.spacing }, { width: 40, height: 30 }, locked); const result = applyResizeSnap(current.node, intended, current.handle, snapped, locked); setGuides(snapped.guides); if (result) onResize(current.node, result, true); } }
    if (current.type === 'marquee') { const box = { start: current.start, end: point }; setMarquee(box); const inside = layout.nodes.filter((node) => intersects(node, box)).map((node) => node.id); onSelection(createNodeSelection([...current.original, ...inside], inside.at(-1))); }
    if (current.type === 'waypoint') { let next = point; if (current.routing === 'orthogonal') { const route = layout.edges.find((edge) => edge.id === current.edgeId)?.points; const previous = route?.[current.index]; const following = route?.[current.index + 2]; if (previous && following) { const candidates = [{ x: previous.x, y: following.y }, { x: following.x, y: previous.y }]; next = candidates.sort((a, b) => Math.hypot(a.x - point.x, a.y - point.y) - Math.hypot(b.x - point.x, b.y - point.y))[0] ?? point; } } current.moved = true; onWaypointMove(current.edgeId, current.index, next); }
  };
  const finishGesture = () => { const current = gesture.current; if (!current) return; gesture.current = undefined; setMarquee(undefined); setGuides([]); if (current.type === 'nodes') { if (!current.moved) onSelection(createNodeSelection([current.primaryId], current.primaryId)); onGestureEnd(); } else if (current.type === 'resize' || current.type === 'waypoint') onGestureEnd(); };
  const doubleClick = (event: MouseEvent<HTMLDivElement>) => { const edgeId = (event.target as Element).closest<SVGElement>('[data-overlay-edge]')?.dataset.overlayEdge; const routing = edgeId ? workspace.layout.edges[edgeId]?.routing ?? 'auto' : undefined; if (!edgeId || routing === 'orthogonal' || routing === 'bezier' || workspace.layout.edges[edgeId]?.routingLocked) return; const matrix = (event.currentTarget.querySelector<SVGSVGElement>('.diagram-output svg')?.getScreenCTM()?.inverse()); const route = layout.edges.find((edge) => edge.id === edgeId)?.points; if (!matrix || !route) return; const raw = new DOMPoint(event.clientX, event.clientY).matrixTransform(matrix); const projected = nearestRouteSegment({ x: raw.x, y: raw.y }, route); if (projected) { onWaypointInsert(edgeId, projected.point, projected.segmentIndex); const waypointIndex = routing === 'manual' ? Math.min(projected.segmentIndex, workspace.layout.edges[edgeId]?.waypoints?.length ?? 0) : 0; onSelection({ type: 'edge', edgeId, waypointIndex }); } };
  const fitSelection = () => { const canvas = canvasRef.current; if (!canvas) return; let target: Bounds | undefined; if (selection?.type === 'nodes') target = selectionBounds(layout.nodes.filter((node) => selection.nodeIds.includes(node.id)).map((node) => ({ ...node, locked: false }))); if (selection?.type === 'edge') target = boundsFromPoints(layout.edges.find((edge) => edge.id === selection.edgeId)?.points ?? []); if (!target) return; const transform = calculateViewportTransform({ width: canvas.clientWidth, height: canvas.clientHeight }, layoutBounds(layout), target); setMode('manual'); setScale(transform.scale); setPan({ x: transform.panX, y: transform.panY }); };
  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!editable) return; if (event.key === 'Escape') { onSelection(undefined); return; } if ((event.key === 'Delete' || event.key === 'Backspace') && selection?.type === 'edge' && selection.waypointIndex !== undefined) { event.preventDefault(); onWaypointDelete(selection.edgeId, selection.waypointIndex); onSelection({ type: 'edge', edgeId: selection.edgeId }); return; } if (selection?.type !== 'nodes') return; const deltas: Record<string, [number, number]> = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }; const delta = deltas[event.key]; if (!delta) return; event.preventDefault(); const amount = event.shiftKey ? 10 : 1; onTranslate(layout.nodes.filter((node) => selection.nodeIds.includes(node.id)), delta[0] * amount, delta[1] * amount, selection.primaryNodeId, false); };
  return <div ref={canvasRef} className={`canvas ${editable ? 'editable' : ''} ${workspace.layout.grid.visible ? 'grid' : ''}`} style={{ '--grid': `${workspace.layout.grid.spacing * scale}px` } as CSSProperties} tabIndex={0} onFocus={() => { if (editable) clearNativeSelection(); }} onDragStart={(event) => { if (editable) event.preventDefault(); }} onKeyDown={keyDown} onWheel={(event) => { event.preventDefault(); setMode('manual'); setScale((value) => clampZoom(value - event.deltaY * .001)); }} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={finishGesture} onPointerCancel={finishGesture} onLostPointerCapture={finishGesture} onDoubleClick={doubleClick}>
    <div className="diagram" style={{ width: layout.width, height: layout.height, marginLeft: -layout.width / 2, marginTop: -layout.height / 2, transform: `translate(${pan.x}px,${pan.y}px) scale(${scale})` }}><div className="diagram-output" dangerouslySetInnerHTML={{ __html: svg }}/>{editable && <EditorOverlay layout={layout} workspace={workspace} selection={selection} scale={scale} guides={guides} {...(marquee ? { marquee } : {})}/>}</div>
    <div className="zoom-tools"><label className="object-snap"><input aria-label="Snap to objects" type="checkbox" checked={objectSnap} onChange={(event) => setObjectSnap(event.target.checked)}/> Objects</label><button aria-label="Zoom out" onClick={() => { setMode('manual'); setScale(clampZoom(scale - ZOOM_STEP)); }}>−</button><output>{Math.round(scale * 100)}%</output><button aria-label="Zoom in" onClick={() => { setMode('manual'); setScale(clampZoom(scale + ZOOM_STEP)); }}>+</button><button aria-label="Set zoom to 100%" onClick={() => { setMode('manual'); setScale(1); setPan({ x: 0, y: 0 }); }}>100%</button><button onClick={() => { setMode('fit'); fit(); }}>Fit</button><button aria-label="Fit selection" disabled={!selection} onClick={fitSelection}>Fit Selection</button><span className="zoom-range" aria-hidden="true">{MIN_ZOOM * 100}–{MAX_ZOOM * 100}%</span></div>
  </div>;
}
