import { describe, expect, it } from 'vitest';
import { applyNodeResize, applyResizeSnap, boundsFromPoints, calculateCanvasGridTransform, calculateViewportTransform, centerLockedResize, createWorkspace, effectiveResizeDelta, insertEdgeWaypoint, nearestPointOnSegment, nearestRouteSegment, nodeBounds, resizeFromHandle, selectionBounds, snapBounds, snapResize, type Bounds, type ResizeHandle } from '@sculpt/workspace';
const frame = { id: 'a', x: 100, y: 100, width: 80, height: 60, locked: false };
describe('direct resize geometry', () => {
  it.each<[ResizeHandle, number, number, object]>([['e', 20, 0, { x: 110, width: 100, y: 100, height: 60 }], ['w', -20, 0, { x: 90, width: 100 }], ['n', 0, -20, { y: 90, height: 80 }], ['s', 0, 20, { y: 110, height: 80 }], ['ne', 20, -20, { x: 110, y: 90, width: 100, height: 80 }], ['se', 20, 20, { x: 110, y: 110, width: 100, height: 80 }], ['sw', -20, 20, { x: 90, y: 110, width: 100, height: 80 }], ['nw', -20, -20, { x: 90, y: 90, width: 100, height: 80 }]])('resizes %s around the opposite edge', (handle, dx, dy, expected) => expect(resizeFromHandle(frame, handle, dx, dy)).toMatchObject(expected));
  it('clamps at useful minimums without flipping', () => expect(resizeFromHandle(frame, 'w', 500, 0)).toEqual({ x: 120, y: 100, width: 40, height: 60 }));
  it('rejects invalid geometry and applies complete manual metadata', () => { expect(resizeFromHandle(frame, 'e', Number.NaN, 0)).toBeUndefined(); const workspace = createWorkspace('resize'); const result = applyNodeResize(workspace, 'a', { x: 2, y: 3, width: 40, height: 30 }); expect(result.layout.nodes.a).toMatchObject({ x: 2, y: 3, width: 40, height: 30, positioning: 'manual', sizing: 'manual' }); expect(applyNodeResize(workspace, 'a', { x: 0, y: 0, width: Infinity, height: 2 })).toBe(workspace); });
  it.each(['e', 'w', 'n', 's', 'ne', 'se', 'sw', 'nw'] as const)('keeps a locked %s resize at the rendered center', (handle) => { const workspace = createWorkspace(`locked-${handle}`); workspace.layout.nodes.a = { positionLocked: true }; const resized = resizeFromHandle(frame, handle, handle.includes('e') ? 20 : handle.includes('w') ? -20 : 0, handle.includes('s') ? 20 : handle.includes('n') ? -20 : 0)!; const result = applyNodeResize(workspace, 'a', resized, frame); expect(result.layout.nodes.a).toMatchObject({ x: 100, y: 100, positionLocked: true }); expect(result.layout.nodes.a?.width).toBe(resized.width); expect(result.layout.nodes.a?.height).toBe(resized.height); });
});
describe('selection bounds', () => {
  it('handles one, several differently-sized, and negative nodes', () => { expect(nodeBounds(frame)).toMatchObject({ left: 60, right: 140, top: 70, bottom: 130 }); expect(selectionBounds([frame, { ...frame, x: -50, y: -40, width: 20, height: 40 }])).toEqual({ left: -60, right: 140, top: -60, bottom: 130, x: 40, y: 35, width: 200, height: 190 }); });
});
describe('object snapping', () => {
  const moving = nodeBounds({ x: 106, y: 100, width: 40, height: 40 })!; const target = nodeBounds({ x: 150, y: 100, width: 40, height: 40 })!;
  it('snaps edges and centers at screen-space tolerance', () => { expect(snapBounds(moving, [{ id: 'b', bounds: target }], 1)).toMatchObject({ dx: 4, dy: 0 }); expect(snapBounds(moving, [{ id: 'b', bounds: target }], 8).dx).toBe(0); });
  it('uses deterministic stable-ID ties and no candidate outside tolerance', () => { const result = snapBounds(moving, [{ id: 'z', bounds: target }, { id: 'a', bounds: target }], 1); expect(result.guides[0]?.targetId).toBe('a'); expect(snapBounds(nodeBounds({ x: 0, y: 0, width: 10, height: 10 })!, [{ id: 'b', bounds: target }], 1).guides).toEqual([]); });
  it('chooses the closest adjustment between grid and objects', () => { expect(snapBounds(moving, [{ id: 'b', bounds: target }], 1, 6, { enabled: true, spacing: 10 }).dx).toBe(4); const gridWins = snapBounds(nodeBounds({ x: 91, y: 100, width: 40, height: 40 })!, [{ id: 'b', bounds: target }], 1, 10, { enabled: true, spacing: 10 }); expect(gridWins.dx).toBe(-1); });
  it('uses an explicit movable node as the group grid reference', () => { const group = { left: 75, right: 175, top: 80, bottom: 120, x: 125, y: 100, width: 100, height: 40 }; const snap = snapBounds(group, [], 1, 6, { enabled: true, spacing: 20, reference: { x: 103, y: 101 } }); expect(snap).toMatchObject({ dx: -3, dy: -1 }); expect((103 + snap.dx) % 20).toBe(0); });
  it('lets group object and reference-grid candidates compete per axis', () => { const group = { left: 75, right: 175, top: 80, bottom: 120, x: 125, y: 100, width: 100, height: 40 }; const objectWins = snapBounds(group, [{ id: 'locked', bounds: { ...group, left: 177, right: 217, x: 197, width: 40 } }], 1, 6, { enabled: true, spacing: 20, reference: { x: 103, y: 100 } }); expect(objectWins.dx).toBe(2); expect(objectWins.guides.find((guide) => guide.axis === 'x')?.targetId).toBe('locked'); const gridWins = snapBounds(group, [{ id: 'target', bounds: { ...group, left: 179, right: 219, x: 199, width: 40 } }], 1, 6, { enabled: true, spacing: 20, reference: { x: 101, y: 100 } }); expect(gridWins.dx).toBe(-1); expect(gridWins.guides.some((guide) => guide.axis === 'x')).toBe(false); });
});
describe('resize-specific snapping', () => {
  const bounds = (left: number, right: number, top = 0, bottom = 100): Bounds => ({ left, right, top, bottom, x: (left + right) / 2, y: (top + bottom) / 2, width: right - left, height: bottom - top }); const original = bounds(0, 100); const target = (value: Bounds) => [{ id: 'target', bounds: value }];
  it('ignores stationary left and center features for east resize', () => { expect(snapResize(original, bounds(0, 197), 'e', target(bounds(0, 200)), 1).dx).toBe(3); expect(snapResize(original, bounds(0, 147), 'e', target(bounds(-50, 150)), 1).dx).toBe(3); });
  it.each([['w', bounds(3, 100), bounds(0, 80), -3, 0], ['n', bounds(0, 100, 3, 100), bounds(20, 120, 0, 80), 0, -3], ['s', bounds(0, 100, 0, 197), bounds(20, 120, 20, 200), 0, 3]] as const)('snaps the active %s edge', (handle, intended, reference, dx, dy) => expect(snapResize(original, intended, handle, target(reference), 1)).toMatchObject({ dx, dy }));
  it('snaps corner axes independently', () => expect(snapResize(original, bounds(0, 197, 3, 100), 'ne', target(bounds(20, 200, 0, 80)), 1)).toMatchObject({ dx: 3, dy: -3 }));
  it('snaps east and west edges to grid lines', () => { const grid = { enabled: true, spacing: 20 }; expect(snapResize(original, bounds(0, 197), 'e', [], 1, 6, grid).dx).toBe(3); expect(snapResize(original, bounds(3, 100), 'w', [], 1, 6, grid).dx).toBe(-3); });
  it('chooses the closer grid or object adjustment', () => expect(snapResize(original, bounds(0, 198), 'e', target(bounds(20, 202)), 1, 6, { enabled: true, spacing: 20 }).dx).toBe(2));
  it('keeps tolerance screen-space at high zoom', () => { expect(snapResize(original, bounds(0, 199.3), 'e', target(bounds(20, 200)), 8).dx).toBeCloseTo(.7); expect(snapResize(original, bounds(0, 199.2), 'e', target(bounds(20, 200)), 8).dx).toBe(0); });
  it('derives final snap geometry from the minimum-clamped edge', () => { const node = { x: 50, y: 50, width: 100, height: 100 }; const clamped = resizeFromHandle(node, 'e', -500, 0)!; const originalBounds = nodeBounds(node)!; const intendedBounds = nodeBounds(clamped)!; expect(effectiveResizeDelta(originalBounds, intendedBounds, 'e')).toEqual({ x: -60, y: 0 }); const snapped = snapResize(originalBounds, intendedBounds, 'e', target(bounds(0, 42, 0, 100)), 1); const result = applyResizeSnap(node, clamped, 'e', snapped)!; expect(result.width).toBe(42); expect(nodeBounds(result)?.right).toBe(42); expect(snapped.guides[0]?.position).toBe(42); });
  it.each([['w', bounds(58, 100), 'w', 58], ['n', bounds(0, 100, 68, 100), 'n', 68], ['s', bounds(0, 100, 0, 32), 's', 32]] as const)('applies outward %s snaps from clamped geometry', (_, targetBounds, handle, expected) => { const node = { x: 50, y: 50, width: 100, height: 100 }; const raw = handle === 'w' ? { x: 500, y: 0 } : handle === 'n' ? { x: 0, y: 500 } : { x: 0, y: -500 }; const clamped = resizeFromHandle(node, handle, raw.x, raw.y)!; const snap = snapResize(nodeBounds(node)!, nodeBounds(clamped)!, handle, target(targetBounds), 1); const result = applyResizeSnap(node, clamped, handle, snap)!; expect(snap.guides[0]?.position).toBe(expected); expect(handle === 'w' ? nodeBounds(result)?.left : handle === 'n' ? nodeBounds(result)?.top : nodeBounds(result)?.bottom).toBe(snap.guides[0]?.position); });
  it('rejects below-minimum object and grid snaps without phantom guides', () => { const intended = bounds(0, 40); const below = snapResize(original, intended, 'e', target(bounds(0, 38)), 1); expect(below).toEqual({ dx: 0, dy: 0, guides: [] }); expect(snapResize(original, bounds(3, 45), 'e', [], 1, 6, { enabled: true, spacing: 20 })).toEqual({ dx: 0, dy: 0, guides: [] }); });
  it('rejects below-minimum height snaps and independently snaps attainable corner axes', () => { const clamped = bounds(0, 40, 70, 100); expect(snapResize(original, clamped, 'ne', target(bounds(0, 42, 72, 100)), 1)).toEqual({ dx: 2, dy: 0, guides: [{ axis: 'x', position: 42, source: 'end', targetId: 'target' }] }); const both = snapResize(original, clamped, 'ne', target(bounds(0, 42, 68, 100)), 1); expect(both).toMatchObject({ dx: 2, dy: -2 }); expect(both.guides.map((guide) => guide.position)).toEqual([42, 68]); });
  it('supports center-locked resize and rejects unattainable snaps', () => { const node = { x: 50, y: 50, width: 100, height: 100 }; const intended = centerLockedResize(node, resizeFromHandle(node, 'e', -500, 0)!); const snap = snapResize(nodeBounds(node)!, nodeBounds(intended)!, 'e', target(bounds(0, 38)), 1, 6, undefined, { width: 40, height: 30 }, true); expect(snap.guides).toEqual([]); expect(applyResizeSnap(node, intended, 'e', snap, true)).toEqual({ x: 50, y: 50, width: 40, height: 100 }); });
});
describe('route projection and insertion', () => {
  it('projects to the nearest segment with stable ordering', () => { expect(nearestPointOnSegment({ x: 4, y: 3 }, { x: 0, y: 0 }, { x: 10, y: 0 })).toEqual({ point: { x: 4, y: 0 }, distance: 3 }); expect(nearestRouteSegment({ x: 9, y: 6 }, [{ x: 0, y: 0 }, { x: 10, y: 0 }, { x: 10, y: 10 }])).toMatchObject({ point: { x: 10, y: 6 }, segmentIndex: 1 }); });
  it('inserts manual waypoints in route order and respects locks', () => { const workspace = createWorkspace('edge'); workspace.layout.edges.e = { routing: 'manual', waypoints: [{ x: 10, y: 0 }] }; const result = insertEdgeWaypoint(workspace, 'e', { x: 5, y: 0 }, 0); expect(result.layout.edges.e?.waypoints).toEqual([{ x: 5, y: 0 }, { x: 10, y: 0 }]); workspace.layout.edges.e.routingLocked = true; expect(insertEdgeWaypoint(workspace, 'e', { x: 5, y: 0 }, 0)).toBe(workspace); });
  it.each(['auto', 'straight'] as const)('starts a fresh manual route from %s without stale waypoints', (routing) => { const workspace = createWorkspace(routing); workspace.layout.edges.e = { routing, waypoints: [{ x: 99, y: 99 }] }; expect(insertEdgeWaypoint(workspace, 'e', { x: 5, y: 6 }, 2).layout.edges.e).toMatchObject({ routing: 'manual', waypoints: [{ x: 5, y: 6 }] }); });
  it('does not directly insert into orthogonal routes', () => { const workspace = createWorkspace('orthogonal'); workspace.layout.edges.e = { routing: 'orthogonal', waypoints: [{ x: 10, y: 0 }] }; expect(insertEdgeWaypoint(workspace, 'e', { x: 5, y: 0 }, 0)).toBe(workspace); });
});
describe('selection viewport framing', () => {
  it('centers off-center and negative targets and clamps zoom', () => { const diagram = { left: -2000, right: 2000, top: -1000, bottom: 1000, x: 0, y: 0, width: 4000, height: 2000 }; expect(calculateViewportTransform({ width: 1000, height: 800 }, diagram, { ...diagram, left: 1650, right: 1750, top: -50, bottom: 50, x: 1700, y: 0, width: 100, height: 100 })).toMatchObject({ scale: 1.5, panX: -2550, panY: 0 }); const points = boundsFromPoints([{ x: -20, y: -10 }, { x: 20, y: 30 }])!; expect(calculateViewportTransform({ width: 20, height: 20 }, points, points).scale).toBe(.2); });
});
describe('Canvas grid transform', () => {
  it('maps diagram origin using the same layout center, pan, and zoom transform', () => { expect(calculateCanvasGridTransform({ x: -40, y: 20, width: 240, height: 100 }, 20, 1.5, { x: 37, y: -11 })).toEqual({ size: 30, offsetX: -83, offsetY: -116 }); });
  it.each([.2, 1, 1.5, 8])('scales lattice spacing at %s zoom without changing pan units', (scale) => { const result = calculateCanvasGridTransform({ x: -100, y: -50, width: 200, height: 100 }, 20, scale, { x: 37, y: -19 })!; expect(result).toEqual({ size: 20 * scale, offsetX: 37, offsetY: -19 }); });
});
