import { expect, it } from 'vitest';
import { parse, render } from '@sculpt/core';
import { DagreLayoutEngine, resolveLayout } from '@sculpt/layout';
import { createWorkspace, moveNode, setEdgeRouting } from '@sculpt/workspace';
it('resolves manual node centers without mutating source', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); let workspace = createWorkspace('manual'); workspace = moveNode(workspace, 'A', 425, 220); const resolved = resolveLayout(ast, new DagreLayoutEngine().layout(ast), workspace.layout); expect(resolved.nodes.find((node) => node.id === 'A')).toMatchObject({ x: 425, y: 220 }); expect(workspace.source).not.toContain('x='); });
it('renders explicit anchors and waypoints deterministically', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const edgeId = ast.edges[0]!.id; const workspace = createWorkspace('route'); workspace.layout.edges[edgeId] = { routing: 'manual', sourceAnchor: 'south', targetAnchor: 'north', waypoints: [{ x: 100, y: 160 }, { x: 200, y: 160 }] }; const result = render('manual-route', source, { metadata: workspace.layout }); expect(result.svg).toContain('100.0,160.0 200.0,160.0'); expect(result.svg).toBe(render('manual-route', source, { metadata: workspace.layout }).svg); });
it('rejects malformed manual waypoint geometry', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const workspace = createWorkspace('unsafe'); workspace.layout.edges[ast.edges[0]!.id] = { routing: 'manual', waypoints: [{ x: Number.NaN, y: 4 }] }; expect(() => render('unsafe', source, { metadata: workspace.layout })).toThrow(/finite coordinates/); });
it('rejects non-orthogonal explicit routes', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const workspace = createWorkspace('orthogonal'); workspace.layout.edges[ast.edges[0]!.id] = { routing: 'orthogonal', sourceAnchor: 'east', targetAnchor: 'west', waypoints: [{ x: 100, y: 100 }] }; expect(() => render('orthogonal', source, { metadata: workspace.layout })).toThrow(/horizontal or vertical/); });
it('keeps negative manual geometry inside the SVG viewBox', () => { const source = 'flowchart LR\nA --> B'; let workspace = createWorkspace('negative'); workspace = moveNode(workspace, 'A', -200, -100); const result = render('negative', source, { metadata: workspace.layout }); expect(result.layout.x).toBeLessThan(-200); expect(result.layout.y).toBeLessThan(-100); expect(result.svg).toContain(`viewBox="${Math.floor(result.layout.x)} ${Math.floor(result.layout.y)}`); });
it('applies manual sizing without forcing manual positioning', () => { const source = 'flowchart LR\nA --> B'; const workspace = createWorkspace('sizing'); workspace.layout.nodes.A = { width: 160, height: 80, sizing: 'manual', positioning: 'auto' }; const result = render('sizing', source, { metadata: workspace.layout }); expect(result.layout.nodes.find((node) => node.id === 'A')).toMatchObject({ width: 160, height: 80 }); expect(workspace.layout.nodes.A.x).toBeUndefined(); });
it('reconnects automatic edges to manually moved nodes', () => { const source = 'flowchart LR\nA --> B'; let workspace = createWorkspace('reconnect'); workspace = moveNode(workspace, 'A', -100, 250); const result = render('reconnect', source, { metadata: workspace.layout }); const moved = result.layout.nodes.find((node) => node.id === 'A')!; const route = result.layout.edges[0]!.points; expect(route[0]?.x === moved.x || route[0]?.y === moved.y).toBe(true); expect(route.at(-1)).not.toEqual(route[0]); });
it('creates a valid deterministic elbow for orthogonal routing without waypoints', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const workspace = createWorkspace('elbow'); workspace.layout.edges[ast.edges[0]!.id] = { routing: 'orthogonal' }; const route = render('elbow', source, { metadata: workspace.layout }).layout.edges[0]!.points; expect(route).toHaveLength(4); expect(route.every((point, index) => index === 0 || point.x === route[index - 1]!.x || point.y === route[index - 1]!.y)).toBe(true); });

it('ignores stored manual waypoints in straight routing', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const edgeId = ast.edges[0]!.id; let workspace = createWorkspace('manual-straight'); workspace.layout.edges[edgeId] = { routing: 'manual', waypoints: [{ x: 321, y: 654 }] }; workspace = setEdgeRouting(workspace, edgeId, 'straight'); const route = render('straight', source, { metadata: workspace.layout }).layout.edges[0]!.points; expect(route).toHaveLength(2); expect(route).not.toContainEqual({ x: 321, y: 654 }); });

it('ignores stored manual waypoints in auto routing', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const edgeId = ast.edges[0]!.id; const workspace = createWorkspace('manual-auto'); workspace.layout.edges[edgeId] = { routing: 'auto', waypoints: [{ x: 321, y: 654 }] }; const route = render('auto', source, { metadata: workspace.layout }).layout.edges[0]!.points; expect(route).not.toContainEqual({ x: 321, y: 654 }); });

it('reactivates preserved waypoints when switching straight to manual', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const edgeId = ast.edges[0]!.id; let workspace = createWorkspace('straight-manual'); workspace.layout.edges[edgeId] = { routing: 'straight', waypoints: [{ x: 321, y: 654 }] }; workspace = setEdgeRouting(workspace, edgeId, 'manual'); expect(render('manual-again', source, { metadata: workspace.layout }).layout.edges[0]!.points).toContainEqual({ x: 321, y: 654 }); });

it('applies auto anchors without reactivating stored manual waypoints', () => { const source = 'flowchart LR\nA --> B'; const ast = parse(source); const edgeId = ast.edges[0]!.id; const workspace = createWorkspace('auto-anchor'); workspace.layout.edges[edgeId] = { routing: 'auto', sourceAnchor: 'north', waypoints: [{ x: 321, y: 654 }] }; const route = render('auto-anchor', source, { metadata: workspace.layout }).layout.edges[0]!.points; expect(route).toHaveLength(2); expect(route).not.toContainEqual({ x: 321, y: 654 }); const sourceNode = render('auto-anchor', source, { metadata: workspace.layout }).layout.nodes.find((node) => node.id === 'A')!; expect(route[0]).toEqual({ x: sourceNode.x, y: sourceNode.y - sourceNode.height / 2 }); });
it('places rerouted labels at the polyline arc-length midpoint', () => { const source = 'flowchart LR\nA -->|label| B'; const ast = parse(source); const workspace = createWorkspace('label-midpoint'); workspace.layout.edges[ast.edges[0]!.id] = { routing: 'straight' }; const edge = render('label-midpoint', source, { metadata: workspace.layout }).layout.edges[0]!; expect(edge.label).toEqual({ x: (edge.points[0]!.x + edge.points[1]!.x) / 2, y: (edge.points[0]!.y + edge.points[1]!.y) / 2 }); expect(edge.label).not.toEqual(edge.points[1]); });
