import { describe, expect, it } from 'vitest';
import { addEdgeWaypoint, alignNodes, createWorkspace, deleteEdgeWaypoint, distributeNodes, matchNodeSize, moveEdgeWaypoint, setEdgeAnchor, setEdgeRouting, translateNodes, updateEdgeGeometry, type NodeFrame } from '@sculpt/workspace';
const frames: NodeFrame[] = [
  { id: 'a', x: 50, y: 50, width: 20, height: 40, locked: false },
  { id: 'b', x: 130, y: 100, width: 40, height: 20, locked: false },
  { id: 'c', x: 250, y: 170, width: 60, height: 60, locked: false },
];
const position = (result: ReturnType<typeof createWorkspace>, id: string) => result.layout.nodes[id];
describe('precision geometry', () => {
  it('translates a group consistently and leaves locked nodes fixed', () => { const locked = frames.map((frame) => frame.id === 'b' ? { ...frame, locked: true } : frame); const result = translateNodes(createWorkspace('move'), locked, 10, -5, 'a'); expect(position(result, 'a')).toMatchObject({ x: 60, y: 45 }); expect(position(result, 'b')).toBeUndefined(); expect(position(result, 'c')).toMatchObject({ x: 260, y: 165 }); });
  it.each([['left', { a: 50, b: 60, c: 70 }], ['right', { a: 270, b: 260, c: 250 }], ['h-center', { a: 160, b: 160, c: 160 }]] as const)('aligns %s with different widths', (alignment, expected) => { const result = alignNodes(createWorkspace(alignment), frames, alignment); for (const [id, x] of Object.entries(expected)) expect(position(result, id)?.x).toBe(x); });
  it.each([['top', { a: 50, b: 40, c: 60 }], ['bottom', { a: 180, b: 190, c: 170 }], ['v-center', { a: 115, b: 115, c: 115 }]] as const)('aligns %s with different heights', (alignment, expected) => { const result = alignNodes(createWorkspace(alignment), frames, alignment); for (const [id, y] of Object.entries(expected)) expect(position(result, id)?.y).toBe(y); });
  it('keeps locked nodes fixed while using them as alignment references', () => { const input = frames.map((frame) => frame.id === 'a' ? { ...frame, locked: true } : frame); const result = alignNodes(createWorkspace('locked'), input, 'left'); expect(position(result, 'a')).toBeUndefined(); expect(position(result, 'b')?.x).toBe(60); });
  it('distributes equal horizontal bounding-box gaps deterministically', () => { const shuffled = [frames[2]!, frames[0]!, frames[1]!]; const result = distributeNodes(createWorkspace('horizontal'), shuffled, 'horizontal'); const a = position(result, 'a')!; const b = position(result, 'b')!; const c = position(result, 'c')!; expect((b.x! - 20) - (a.x! + 10)).toBeCloseTo((c.x! - 30) - (b.x! + 20)); });
  it('distributes equal vertical gaps and no-ops below three nodes', () => { const workspace = createWorkspace('vertical'); const result = distributeNodes(workspace, frames, 'vertical'); const a = position(result, 'a')!; const b = position(result, 'b')!; const c = position(result, 'c')!; expect((b.y! - 10) - (a.y! + 20)).toBeCloseTo((c.y! - 30) - (b.y! + 10)); expect(distributeNodes(workspace, frames.slice(0, 2), 'horizontal')).toBe(workspace); });
  it('matches width and height to the primary node', () => { const width = matchNodeSize(createWorkspace('width'), frames, 'b', 'width'); expect(position(width, 'a')?.width).toBe(40); expect(position(width, 'c')?.width).toBe(40); const height = matchNodeSize(createWorkspace('height'), frames, 'c', 'height'); expect(position(height, 'a')?.height).toBe(60); expect(position(height, 'b')?.height).toBe(60); });
});
describe('edge precision geometry', () => {
  it('updates anchors and waypoint lifecycle', () => { let workspace = createWorkspace('edge'); workspace = setEdgeAnchor(workspace, 'edge-1', 'source', 'east'); workspace = addEdgeWaypoint(workspace, 'edge-1', { x: 10, y: 20 }); workspace = moveEdgeWaypoint(workspace, 'edge-1', 0, { x: 30, y: 40 }); expect(workspace.layout.edges['edge-1']).toMatchObject({ sourceAnchor: 'east', routing: 'manual', waypoints: [{ x: 30, y: 40 }] }); workspace = deleteEdgeWaypoint(workspace, 'edge-1', 0); expect(workspace.layout.edges['edge-1']?.waypoints).toEqual([]); });
  it('rejects invalid waypoints and respects routing locks', () => { const workspace = createWorkspace('locked-edge'); workspace.layout.edges.edge = { routing: 'manual', routingLocked: true, waypoints: [{ x: 1, y: 2 }] }; expect(moveEdgeWaypoint(workspace, 'edge', 0, { x: 3, y: 4 })).toBe(workspace); expect(addEdgeWaypoint(workspace, 'edge', { x: Number.NaN, y: 0 })).toBe(workspace); expect(updateEdgeGeometry(workspace, 'edge', { sourceAnchor: 'west' })).toBe(workspace); expect(setEdgeRouting(workspace, 'edge', 'straight')).toBe(workspace); });
});
