import { test, expect, type Page } from '@playwright/test';
const open = async (page: Page, name: string) => { await page.goto(`/workspace/${name}?view=split`); await expect(page.locator('.diagram-output svg')).toBeVisible(); };
const node = (page: Page, id: string) => page.locator(`[data-overlay-node="${id}"]`);
const center = async (locator: ReturnType<typeof node>) => { const box = await locator.boundingBox(); if (!box) throw new Error('Element bounds unavailable'); return { x: box.x + box.width / 2, y: box.y + box.height / 2 }; };
test('automatic split view renders its flowchart', async ({ page }) => { await open(page, 'visual-auto-v3'); expect(await page.locator('.preview').screenshot()).toMatchSnapshot('automatic-preview.png'); });
test('manual dimensions and precision inspector', async ({ page }) => { await open(page, 'visual-manual-v3'); await node(page, 'idea').click(); await page.getByLabel('Node X').fill('425'); await page.getByLabel('Node Y').fill('220'); await page.getByLabel('Node width').fill('120'); await page.getByLabel('Node height').fill('64'); await expect(page.getByLabel('Node width')).toHaveValue('120'); await expect(node(page, 'idea')).toHaveAttribute('width', '120'); await expect(node(page, 'idea')).toHaveAttribute('height', '64'); await page.locator('.inspector .panel-title').click(); expect(await page.locator('.workspace-shell').screenshot()).toMatchSnapshot('manual-inspector.png'); });
test('preview-only view minimizes chrome', async ({ page }) => { await page.goto('/workspace/visual-preview-v3?view=preview'); await expect(page.locator('.editor')).toHaveCount(0); await expect(page.locator('.diagram-output svg')).toBeVisible(); expect(await page.locator('.workspace-shell').screenshot()).toMatchSnapshot('preview-only.png'); });
test('modifier click selects multiple nodes and alignment updates geometry', async ({ page }) => { await open(page, 'multi-align'); await node(page, 'idea').click(); await node(page, 'build').click({ modifiers: ['Control'] }); await expect(page.locator('.node-hit.selected')).toHaveCount(2); await page.getByLabel('Align nodes').selectOption('left'); await expect.poll(async () => page.locator('.node-hit.selected').evaluateAll((items) => items.map((item) => Number(item.getAttribute('x'))))).toEqual([24, 24]); });
test('marquee selects intersecting nodes', async ({ page }) => { await open(page, 'marquee'); const first = await node(page, 'idea').boundingBox(); const second = await node(page, 'build').boundingBox(); if (!first || !second) throw new Error('Node bounds unavailable'); await page.mouse.move(first.x - 4, Math.min(first.y, second.y) - 4); await page.mouse.down(); await page.mouse.move(second.x + second.width + 4, Math.max(first.y + first.height, second.y + second.height) + 4); await page.mouse.up(); await expect(page.locator('.node-hit.selected')).toHaveCount(2); });
test('workspace undo and redo restore precision edits', async ({ page }) => { await open(page, 'undo-redo'); await node(page, 'idea').click(); const original = await page.getByLabel('Node X').inputValue(); await page.getByLabel('Node X').fill('400'); await page.getByRole('button', { name: 'Undo' }).click(); await expect(page.getByLabel('Node X')).toHaveValue(original); await page.getByRole('button', { name: 'Redo' }).click(); await expect(page.getByLabel('Node X')).toHaveValue('400'); });
test('edge selection exposes routing and draggable waypoint controls', async ({ page }) => { await open(page, 'edge-waypoint'); const edge = page.locator('[data-overlay-edge]').first(); await edge.click({ force: true }); await expect(page.getByLabel('Source anchor')).toBeVisible(); await page.getByLabel('Source anchor').selectOption('east'); await page.getByRole('button', { name: 'Add Waypoint' }).click(); const waypoint = page.locator('[data-waypoint]').first(); await expect(waypoint).toBeVisible(); const before = await waypoint.getAttribute('cx'); const bounds = await waypoint.boundingBox(); if (!bounds) throw new Error('Waypoint bounds unavailable'); await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2); await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 20, bounds.y + bounds.height / 2 + 12); await page.mouse.up(); await expect(waypoint).not.toHaveAttribute('cx', before ?? ''); });
test('cancelled waypoint drag remains one undoable transaction', async ({ page }) => { await open(page, 'waypoint-cancel'); await page.locator('[data-overlay-edge]').first().click({ force: true }); await page.getByRole('button', { name: 'Add Waypoint' }).click(); const waypoint = page.locator('[data-waypoint]').first(); const original = Number(await waypoint.getAttribute('cx')); const point = await center(waypoint); await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(point.x + 25, point.y + 10); await page.locator('.canvas').dispatchEvent('pointercancel', { pointerId: 1, clientX: point.x + 25, clientY: point.y + 10 }); await page.mouse.up(); await page.getByRole('button', { name: 'Undo' }).click(); await expect.poll(async () => Number(await waypoint.getAttribute('cx'))).toBeCloseTo(original, 1); });
test('long node and group drags remain stable across expanded bounds', async ({ page }) => { await open(page, 'stable-drag'); await page.getByLabel('Set zoom to 100%').click(); await node(page, 'idea').click(); const original = Number(await page.getByLabel('Node X').inputValue()); const start = await center(node(page, 'idea')); await page.mouse.move(start.x, start.y); await page.mouse.down(); await page.mouse.move(start.x + 220, start.y, { steps: 4 }); await page.waitForTimeout(150); await page.mouse.move(start.x + 360, start.y, { steps: 4 }); await page.mouse.up(); await expect.poll(async () => Number(await page.getByLabel('Node X').inputValue())).toBeCloseTo(original + 360, 0); await open(page, 'stable-group'); await page.getByLabel('Set zoom to 100%').click(); await node(page, 'idea').click(); await node(page, 'build').click({ modifiers: ['Control'] }); await expect(page.locator('.node-hit.selected')).toHaveCount(2); const groupOriginal = Number(await node(page, 'idea').getAttribute('x')); const groupStart = await center(node(page, 'idea')); await page.mouse.move(groupStart.x, groupStart.y); await page.mouse.down(); await page.mouse.move(groupStart.x + 220, groupStart.y, { steps: 4 }); await page.waitForTimeout(150); await page.mouse.move(groupStart.x + 360, groupStart.y, { steps: 4 }); await page.mouse.up(); await expect.poll(async () => Number(await node(page, 'idea').getAttribute('x'))).toBeCloseTo(groupOriginal + 360, 0); });
test('cancelled and lost-capture gestures finish independent transactions', async ({ page }) => { await open(page, 'gesture-finalize'); await page.getByLabel('Set zoom to 100%').click(); await node(page, 'idea').click(); const original = Number(await page.getByLabel('Node X').inputValue()); let point = await center(node(page, 'idea')); await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(point.x + 30, point.y); await page.locator('.canvas').dispatchEvent('pointercancel', { pointerId: 1, clientX: point.x + 30, clientY: point.y }); await page.mouse.up(); await expect(page.getByRole('button', { name: 'Undo' })).toBeEnabled(); point = await center(node(page, 'idea')); await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(point.x + 40, point.y); await page.mouse.up(); await page.getByRole('button', { name: 'Undo' }).click(); await expect.poll(async () => Number(await page.getByLabel('Node X').inputValue())).toBeCloseTo(original + 30, 0); await page.getByRole('button', { name: 'Undo' }).click(); await expect.poll(async () => Number(await page.getByLabel('Node X').inputValue())).toBeCloseTo(original, 0); const noOp = await center(node(page, 'idea')); await page.mouse.move(noOp.x, noOp.y); await page.mouse.down(); await page.locator('.canvas').dispatchEvent('lostpointercapture', { pointerId: 1 }); await page.mouse.up(); await expect(page.getByRole('button', { name: 'Undo' })).toBeDisabled(); });
test('large hierarchy auto-fits and shares one aligned display surface', async ({ page }) => { await open(page, 'large-hierarchy'); await page.getByLabel('Diagram source').fill(`flowchart TD
svrcmbdoc22fs[svrcmbdoc22fs]
svrcmbdoc22fs --> nbci_files{nbci_files$}
svrcmbdoc22fs --> wci_files{wci_files$}
nbci_files --> all_departments[All Departments]
all_departments --> business_office[Business Office]
nbci_files --> administration[Administration]
nbci_files --> change_sheets[Change Sheets]
nbci_files --> custody[Custody]
nbci_files --> support_staff{Support Staff}
custody --> case_management[Case Management]
custody --> chaplain[Chaplain]
custody --> case_management_2[Case Management]`); await expect(node(page, 'business_office')).toBeVisible(); const canvas = await page.locator('.canvas').boundingBox(); const diagram = await page.locator('.diagram').boundingBox(); if (!canvas || !diagram) throw new Error('Canvas bounds unavailable'); expect(diagram.width).toBeLessThanOrEqual(canvas.width); expect(diagram.height).toBeLessThanOrEqual(canvas.height); await node(page, 'business_office').click(); const rendered = await page.locator('[data-node-id="business_office"]').boundingBox(); const overlay = await node(page, 'business_office').boundingBox(); if (!rendered || !overlay) throw new Error('Node bounds unavailable'); expect(Math.abs(rendered.x - overlay.x)).toBeLessThan(1); expect(Math.abs(rendered.y - overlay.y)).toBeLessThan(1); await page.getByLabel('Set zoom to 100%').click(); await expect(page.locator('.zoom-tools output')).toHaveText('100%'); await page.getByRole('button', { name: 'Fit' }).click(); await page.setViewportSize({ width: 1100, height: 760 }); await expect.poll(async () => (await page.locator('.diagram').boundingBox())?.width ?? 0).toBeLessThanOrEqual((await page.locator('.canvas').boundingBox())?.width ?? 0); for (let index = 0; index < 60; index += 1) await page.getByLabel('Zoom in').click(); await expect(page.locator('.zoom-tools output')).toHaveText('800%'); });
