import type { Anchor, EdgeGeometry, EdgeRouting, NodeGeometry, Point, Workspace } from './index';
export interface NodeFrame { id: string; x: number; y: number; width: number; height: number; locked: boolean }
export type Alignment = 'left' | 'h-center' | 'right' | 'top' | 'v-center' | 'bottom';
export type Distribution = 'horizontal' | 'vertical';
export type MatchDimension = 'width' | 'height';
const finite = (value: number): boolean => Number.isFinite(value) && Math.abs(value) <= 1_000_000;
const validSize = (value: number): boolean => finite(value) && value > 0;
function withNodes(workspace: Workspace, updates: Map<string, NodeGeometry>): Workspace { if (updates.size === 0) return workspace; return { ...workspace, layout: { ...workspace.layout, mode: workspace.layout.mode === 'auto' ? 'hybrid' : workspace.layout.mode, nodes: { ...workspace.layout.nodes, ...Object.fromEntries(updates) } } }; }
function geometry(workspace: Workspace, frame: NodeFrame): NodeGeometry { const current = workspace.layout.nodes[frame.id]; return { ...current, x: frame.x, y: frame.y, ...(current?.width !== undefined ? { width: current.width } : {}), ...(current?.height !== undefined ? { height: current.height } : {}), positioning: 'manual', sizing: current?.sizing ?? 'auto' }; }
export function translateNodes(workspace: Workspace, frames: NodeFrame[], dx: number, dy: number, snapReferenceId?: string, applyGridSnap = true): Workspace {
  if (!finite(dx) || !finite(dy)) return workspace; const movable = frames.filter((frame) => !frame.locked); if (!movable.length) return workspace; let tx = dx; let ty = dy; const reference = movable.find((frame) => frame.id === snapReferenceId) ?? movable[0]; if (applyGridSnap && workspace.layout.grid.snap && reference) { const spacing = workspace.layout.grid.spacing; tx = Math.round((reference.x + dx) / spacing) * spacing - reference.x; ty = Math.round((reference.y + dy) / spacing) * spacing - reference.y; }
  const updates = new Map<string, NodeGeometry>(); for (const frame of movable) updates.set(frame.id, { ...geometry(workspace, frame), x: frame.x + tx, y: frame.y + ty }); return withNodes(workspace, updates);
}
export function resizeNode(workspace: Workspace, frame: NodeFrame, width: number, height: number): Workspace { if (!validSize(width) || !validSize(height)) return workspace; return withNodes(workspace, new Map([[frame.id, { ...workspace.layout.nodes[frame.id], width, height, sizing: 'manual' }]])); }
export function alignNodes(workspace: Workspace, frames: NodeFrame[], alignment: Alignment): Workspace {
  if (frames.length < 2 || !frames.every((frame) => finite(frame.x) && finite(frame.y) && validSize(frame.width) && validSize(frame.height))) return workspace; const left = Math.min(...frames.map((frame) => frame.x - frame.width / 2)); const right = Math.max(...frames.map((frame) => frame.x + frame.width / 2)); const top = Math.min(...frames.map((frame) => frame.y - frame.height / 2)); const bottom = Math.max(...frames.map((frame) => frame.y + frame.height / 2)); const updates = new Map<string, NodeGeometry>();
  for (const frame of frames) { if (frame.locked) continue; let x = frame.x; let y = frame.y; if (alignment === 'left') x = left + frame.width / 2; if (alignment === 'right') x = right - frame.width / 2; if (alignment === 'h-center') x = (left + right) / 2; if (alignment === 'top') y = top + frame.height / 2; if (alignment === 'bottom') y = bottom - frame.height / 2; if (alignment === 'v-center') y = (top + bottom) / 2; updates.set(frame.id, { ...geometry(workspace, frame), x, y }); } return withNodes(workspace, updates);
}
export function distributeNodes(workspace: Workspace, frames: NodeFrame[], direction: Distribution): Workspace {
  if (frames.length < 3) return workspace; const horizontal = direction === 'horizontal'; const sorted = [...frames].sort((a, b) => (horizontal ? a.x - b.x : a.y - b.y) || a.id.localeCompare(b.id)); const start = sorted[0]; const end = sorted.at(-1); if (!start || !end) return workspace; const totalSize = sorted.reduce((sum, frame) => sum + (horizontal ? frame.width : frame.height), 0); const outerStart = (horizontal ? start.x - start.width / 2 : start.y - start.height / 2); const outerEnd = (horizontal ? end.x + end.width / 2 : end.y + end.height / 2); const gap = (outerEnd - outerStart - totalSize) / (sorted.length - 1); let cursor = outerStart; const updates = new Map<string, NodeGeometry>(); for (const frame of sorted) { const size = horizontal ? frame.width : frame.height; const center = cursor + size / 2; if (!frame.locked) updates.set(frame.id, { ...geometry(workspace, frame), ...(horizontal ? { x: center } : { y: center }) }); cursor += size + gap; } return withNodes(workspace, updates);
}
export function matchNodeSize(workspace: Workspace, frames: NodeFrame[], primaryId: string, dimension: MatchDimension): Workspace { const primary = frames.find((frame) => frame.id === primaryId); if (!primary || frames.length < 2) return workspace; const updates = new Map<string, NodeGeometry>(); for (const frame of frames) { if (frame.id === primaryId) continue; updates.set(frame.id, { ...workspace.layout.nodes[frame.id], width: dimension === 'width' ? primary.width : frame.width, height: dimension === 'height' ? primary.height : frame.height, sizing: 'manual' }); } return withNodes(workspace, updates); }
export function updateEdgeGeometry(workspace: Workspace, edgeId: string, patch: Partial<EdgeGeometry>): Workspace { const current = workspace.layout.edges[edgeId] ?? { routing: 'auto' }; if (current.routingLocked) return workspace; return { ...workspace, layout: { ...workspace.layout, edges: { ...workspace.layout.edges, [edgeId]: { ...current, ...patch } } } }; }
export function setEdgeAnchor(workspace: Workspace, edgeId: string, end: 'source' | 'target', anchor: Anchor): Workspace { return updateEdgeGeometry(workspace, edgeId, end === 'source' ? { sourceAnchor: anchor } : { targetAnchor: anchor }); }
export function setEdgeRouting(workspace: Workspace, edgeId: string, routing: Exclude<EdgeRouting, 'bezier'>): Workspace { return updateEdgeGeometry(workspace, edgeId, { routing }); }
export function addEdgeWaypoint(workspace: Workspace, edgeId: string, point: Point): Workspace { if (!finite(point.x) || !finite(point.y)) return workspace; const current = workspace.layout.edges[edgeId] ?? { routing: 'auto' }; if (current.routingLocked) return workspace; return updateEdgeGeometry(workspace, edgeId, { routing: 'manual', waypoints: [...(current.waypoints ?? []), point] }); }
export function moveEdgeWaypoint(workspace: Workspace, edgeId: string, index: number, point: Point): Workspace { if (!finite(point.x) || !finite(point.y)) return workspace; const current = workspace.layout.edges[edgeId]; if (!current || current.routingLocked || !current.waypoints?.[index]) return workspace; const waypoints = current.waypoints.map((value, waypointIndex) => waypointIndex === index ? point : value); return updateEdgeGeometry(workspace, edgeId, { waypoints }); }
export function deleteEdgeWaypoint(workspace: Workspace, edgeId: string, index: number): Workspace { const current = workspace.layout.edges[edgeId]; if (!current || current.routingLocked || !current.waypoints?.[index]) return workspace; return updateEdgeGeometry(workspace, edgeId, { waypoints: current.waypoints.filter((_, waypointIndex) => waypointIndex !== index) }); }
